# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t5UlltC5kqtYOUI-QuTel-6gfTwmwQPI
"""

# Passo 1: Recebe a resposta do usuário e remove espaços extras nas pontas
resposta = input("Deseja continuar no sistema? (Sim/Não): ").strip()

# Passo 2: Converte o texto para letras minúsculas usando .lower()
if resposta.lower() == "sim":
    print("Continuando...")
else:
    print("Encerrando...")

# Passo 1: Solicita a sigla do estado e remove espaços em branco extras
estado = input("Digite a sigla do seu estado (ex: sp, rj, mg): ").strip()

# Passo 2: Converte a entrada para maiúsculas usando .upper()
estado_padronizado = estado.upper()

# Passo 3: Exibe a mensagem final formatada
print(f"Estado cadastrado: {estado_padronizado}")

# Passo 1: Define o cupom correto no sistema (sempre em maiúsculas)
CUPOM_VALIDO = "DESCONTO10"

# Passo 2: Solicita o cupom ao usuário e remove espaços extras
entrada_usuario = input("Digite o seu cupom promocional: ").strip()

# Passo 3: Converte a entrada para maiúsculas antes da comparação
if entrada_usuario.upper() == CUPOM_VALIDO:
    print("Cupom aplicado com sucesso!")
else:
    print("Cupom inválido.")

# Passo 1: Solicita o primeiro nome do usuário (com possíveis espaços extras)
nome_bruto = input("Digite o seu primeiro nome: ")

# Passo 2: Remove os espaços em branco do início e do fim
nome_limpo = nome_bruto.strip()

# Passo 3: Conta a quantidade de caracteres do nome corrigido
quantidade_caracteres = len(nome_limpo)

# Passo 4: Exibe as informações na tela
print(f"Nome limpo: '{nome_limpo}'")
print(f"Quantidade exata de caracteres: {quantidade_caracteres}")
]

# Passo 1: Solicita o e-mail do usuário
email_usuario = input("Digite o seu e-mail: ")

# Passo 2: Remove espaços invisíveis e valida se o campo ficou vazio
if email_usuario.strip() == "":
    print("Erro: O campo e-mail não pode ficar em branco!")
else:
    print("E-mail cadastrado!")

# Passo 1: Define o usuário correto no sistema (sempre em minúsculas)
USUARIO_CORRETO = "aluno@escola.com"

# Passo 2: Solicita o login, remove espaços extras e converta para minúsculas
login_usuario = input("Digite seu e-mail de login: ").strip().lower()

# Passo 3: Compara a credencial tratada com o valor correto
if login_usuario == USUARIO_CORRETO:
    print("Acesso concedido! Bem-vindo ao sistema.")
else:
    print("Falha no login: Usuário incorreto.")